### ISSUE TITLE
git directory is no longer being properly created

### ISSUE THREAD

**Issue by dream-dasher** [ethanmsl/incarnate#8]
I haven't determined the issue yet.
But unix_wait_status code is `128`, which may indicate ownership issues re: repo vs child shell running command.
This wasn't previously an issue though.  Worth some playing with commands directly and a git bisect (may also be related to mac settings changes).

Current status: repo is created.  a _file_ named `.git` is created, but no initialization.
This also prevents the githooks from being placed appropriately and therefore leaves them unusable.

Everything else works.  
(Notably: there's not currently any error handling for the **status** code of the shell commands.  There's error handling around whether they were run, but not their exit_status of impact.  -- Added some trace logs looking at a few of these, but should create explicit warnings based on exit_status, for example.  See also the nightly: [struct.ExitStatus](https://doc.rust-lang.org/std/process/struct.ExitStatus.html))

**Comment by ethanmsl** [comment]
Fixed!: [incarnate/commit/...e13d8](https://github.com/ethanmsl/incarnate/commit/e5b89505ad5fd2795eca274ef71e10de000e13d8)

When I moved the contents of the assets directory to a git submodule, so templates could be managed separately from the incarnate repo, a new .git element was introduced (actually a `.git` *file*).  This was being copied along with the rest of the pre-hydrated template and blocking `git init` from succeeding.

Of note:
- the error handling for the shell command to do git initialization merely checked whether the shell spawning and execution worked correctly.  Separate handling of the result of that operation (e.g. via returned status_code) is required in order to reason about specific outcomes of command that ran.
- the natural fix would be to simply not include the unwanted element in the binary.  (as we roll up the whole template and embed it directly)  The approach we use does not provide a way of excluding elements.  (an understandable api choice). Which would leave a few options, including cloning most of the template to a temporary file, modifying the individual git submodule (yech) and rollling that or similar non-joint carving (tools sharper than the healthy structures they move in, as it were).  As the size is not an issue I've instead opted to exclude the file during runtime copying/hydration.  If I decide to expand this tools scope or functionality at somepoint a general approach, such as template masking, will likely be needed to enable flexible storage and interface with templates.
